spring.application.name=smart-lost-found
server.port=${PORT:8080}
spring.datasource.url=jdbc:${DB_URL:postgresql://localhost:5432/lost_found}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jackson.serialization.fail-on-empty-beans=false
